### ISSUE TITLE
search filter reads the information too frequently

### ISSUE THREAD

**Issue by tautaus** [CarolineYao/SentimentAnalysisProject#8] opened 2021-04-23 05:26 UTC
I have 2 solutions for now:
1. let the search filter reads the data only when clicks on the submit 
2. let the search filter reads whenever we set an entry "unused"

**Comment by CarolineYao** [comment] 2021-04-24 21:50
Closing this because this is the intended behavior. One thing to note is that the search filter does not affect search results **untill** submit button is clicked.

**Closed as completed by CarolineYao** 2021-04-24 21:50 UTC
